### ISSUE TITLE
RPDB not appearing in certain catalogs, but visible in default Stremio

### ISSUE THREAD

**Issue by CmdPrmpt** [Fxy6969/Stremio-Glass-Theme#7]
Many of my catalogs which have RPDB ratings on the regular stremio are not appearing on stremio enhanced with the theme/plugins enabled. 
I use Stremthru Lists for my catalogs.

<img width="911" height="622" alt="Image" src="https://github.com/user-attachments/assets/4525fc2d-6c72-4a22-b832-bc129cc9f090" />

<img width="971" height="981" alt="Image" src="https://github.com/user-attachments/assets/93d37724-9131-436c-9464-2762e139bb4f" />

**Comment by Fxy6969** [comment]
has been fixed redownload the release.

**Comment by CmdPrmpt** [comment]
@Fxy6969 
Hi I have downloaded the updated release and the problem persists.

<img width="1895" height="1028" alt="Image" src="https://github.com/user-attachments/assets/0539fed5-b6cd-48cc-bfcf-aa62a67f6520" />

**Comment by Fxy6969** [comment]
Hello,

I apologize for any inconvenience caused. Could you please provide a detailed explanation of the problem, as I don’t seem to understand the issue in the screenshots you’ve sent.

Thanks

**Comment by CmdPrmpt** [comment]
Sorry my mistake, I should have clarified as the RPDB posters do show now but the star rating, year, and genre information is missing on about half of my categories. Ex:
<img width="1460" height="564" alt="Image" src="https://github.com/user-attachments/assets/2727c81f-160c-49ee-99e0-dcf2a68f26d0" />
